### ISSUE TITLE
Why global variable?

### ISSUE THREAD

**Issue by buragc** [rolandz83/StockSimulator#4]
https://github.com/rolandz83/StockSimulator/blob/c6017ded69108f526ef10018fb77db772405c1d2/AlphaVantageTK.py#L71

**Comment by rolandz83** [comment]
data is accessed by other functions, it needs to be global. 
the other option is to keep data in api.py and write bunch of get/set functions to and access it in TK.py
which brings us to issue #5 doesn't it ?

**Comment by rolandz83** [comment]
fixed this issue with the new update, no more global !
